name: 'UIC Configuration'
description: 'Custom content types and configuration for UIC project'
type: module
core_version_requirement: ^9 || ^10
package: Custom
dependencies:
  - drupal:node
  - drupal:field
  - drupal:field_ui
  - drupal:user
  - drupal:text
  - drupal:datetime
  - drupal:media
  - drupal:media_library
  - drupal:content_moderation
  - drupal:path
  - drupal:menu_ui
  - drupal:filter
  - drupal:image
  - drupal:taxonomy
  - graphql_compose:graphql_compose
